version: "3.9"
services:
  mynote:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    environment:
    - MYSQL_DATABASE=mynote_db
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql