version: "3.9"
services:

  frontend:
    build: ./mynote-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./mynote-frontend/:/app

  backend:
    build: ./mynote-backend
    environment:
    - MYSQL_DATABASE=mynote_db
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_HOST=db
    - API_KEY=${API_KEY}
    - CX=${CX}
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./mynote-backend/:/app
  db:
    image: mysql:5.7
    environment:
    - MYSQL_DATABASE=mynote_db
    - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql