name: Ginkgo

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mynote_test_db
    name: Ginkgo
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Install Tools
      run: |
        go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
        go get github.com/onsi/gomega/...
    - name: Set environment variables
      run: |
        echo "MYSQL_ROOT_PASSWORD=password" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=mynote_test_db" >> $GITHUB_ENV
    - name: Run test
      run: ginkgo -r --randomize-all --randomize-suites